[tool.black]
line-length = 120
target-version = ['py27', 'py36', 'py37']
force-exclude = 'igibson/(data|external|render/(cpp|cryptopp|glad|glfw|glm|pybind11|sranipal))'

[tool.isort]
profile = "black"
line_length = 120
py_version = 'all'
filter_files = true
extend_skip_glob = [
    'igibson/data/*',
    'igibson/external/*',
    'igibson/render/cpp/*',
    'igibson/render/cryptopp/*',
    'igibson/render/glad/*',
    'igibson/render/glfw/*',
    'igibson/render/glm/*',
    'igibson/render/pybind11/*',
    'igibson/render/sranipal/*',
]

[tool.pyright]
exclude = [
  'igibson/data',
  'igibson/docs',
  'igibson/docker',
  'igibson/render/cryptopp',
  'igibson/render/cpp',
  'igibson/render/glfw',
  'igibson/render/glad',
  'igibson/render/glm',
  'igibson/render/pybind11',
  'igibson/render/sranipal'
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = '--cov=igibson --cov-report=xml'

[tool.coverage.run]
omit = ["igibson/external/*"]
