## SoundSpaces
TORCH_GPU_ID: 0
VIDEO_OPTION: []
# audio to save
AUDIO_DIR: 'example.wav'

## iGibson
scene: igibson
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: with_obj_no_door
trav_map_resolution: 0.1
trav_map_erosion: 2
should_open_all_doors: true
clutter: false
texture_scale: 0.1
not_load_object_categories: ['door', 'doors']

# task
task: audiogoal_nav
target_dist_min: 1.0
target_dist_max: 10.0
goal_format: polar
task_obs_dim: 2

# robot
robot:
    name: Turtlebot
    action_type: continuous
    action_normalize: true
    base_name: null
    scale: 1.0
    self_collision: false
    rendering_params: null
    controller_config:
        base:
            name: JointController
            motor_type: velocity
            command_input_limits: default
            command_output_limits: default
            use_delta_commands: false

# sensor spec
output: [task_obs, depth, audio, bump]
#task_obs, 
extra_rgb: false

# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
image_width: 128
image_height: 128
vertical_fov: 45
# depth
depth_low: 0.8
depth_high: 3.5
# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# audio to play
audio_to_play: "telephone.wav"

# visual objects
visible_target: False

# reward only for point nav fixed task
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.005
time_reward_weight: -0.01

# termination condition
# body width
dist_tol: 0.36 
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links
# discount factor
discount_factor: 0.99
# domain randomization
texture_randomization_freq: null
object_randomization_freq: null
