g_dataset_path: /cvgl/group/Gibson/matterport3d-downsized/v1
threedfront_dataset_path: /viscam/u/wangzz/avGibson/data/threedfront_dataset
cubicasa_dataset_path: /viscam/u/wangzz/avGibson/data/cubicasa_dataset
assets_path: /viscam/projects/sonicverse/iGibson-dev/igibson/data/assets
ig_dataset_path: /viscam/projects/sonicverse/iGibson-dev/igibson/data/ig_dataset
key_path: /viscam/projects/sonicverse/iGibson-dev/igibson/data/igibson.key

