# Example Joint control config (shown for arm control)
# See igibson/controllers/joint_controller for docstring of arguments
# Arguments below are the arguments that should be specified by external user (other kwargs
# used in constructor are generated automatically at runtime)
robot:
  controller_config:
    arm:
      name: JointController
      motor_type: velocity
      command_input_limits: default
      command_output_limits: default
      use_delta_commands: false
