# Example Multi Finger Gripper control config (shown for arm control)
# See igibson/controllers/parallel_jaw_gripper_controller for docstring of arguments
# Arguments below are the arguments that should be specified by external user (other kwargs
# used in constructor are generated automatically at runtime)
robot:
  controller_config:
    arm:
      name: MultiFingerGripperController
      motor_type: position
      command_input_limits: default
      mode: binary
      limit_tolerance: 0.01