# Example BehaviorRobot config
robot:
  name: BehaviorRobot
  action_type: continuous
  action_normalize: false
  proprio_obs:
    - eef_0_pos
    - eef_0_quat
    - arm_0_qpos_sin
    - arm_0_qpos_cos
    - gripper_0_qpos
    - grasp_0
    - eef_1_pos
    - eef_1_quat
    - arm_1_qpos_sin
    - arm_1_qpos_cos
    - gripper_1_qpos
    - grasp_1
  reset_joint_pos: null
  base_name: body
  scale: 1.0
  self_collision: true
  rendering_params: null
  hands:
    - left
    - right
  use_ghost_hands: true
  normal_color: true
  show_visual_head: false
  use_tracked_body: true
  grasping_mode: assisted
  controller_config:
    base:
      name: JointController
    arm_0:
      name: JointController
    gripper_0:
      name: MultiFingerGripperController
    arm_1:
      name: JointController
    gripper_1:
      name: MultiFingerGripperController
    camera:
      name: JointController