# Example Husky config
robot:
  name: Husky
  action_type: continuous
  action_normalize: true
  proprio_obs:
    - joint_qpos
    - joint_qvel
  reset_joint_pos: null
  base_name: null
  scale: 1.0
  self_collision: false
  rendering_params: null
  controller_config:
    base:
      name: JointController