# Example JR2 config
robot:
  name: JR2
  action_type: continuous
  action_normalize: true
  proprio_obs:
    - eef_0_pos
    - eef_0_quat
    - arm_0_qpos_sin
    - arm_0_qpos_cos
  reset_joint_pos: null
  base_name: null
  scale: 1.0
  self_collision: true
  rendering_params: null
  grasping_mode: physical
  controller_config:
    base:
      name: DifferentialDriveController
    arm_0:
      name: InverseKinematicsController
    gripper_0:
      name: NullGripperController